import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './assets/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Suas Coisas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><Header title={metadata.title ? metadata.title.toString() : "404"} ></Header>{children}</body>
    </html>
  )
}
